### ISSUE TITLE
Missing required module 'whisper_cpp' when using the SwiftWhisper code.  

### ISSUE THREAD

**Issue by shyamalschandra** [exPHAT/SwiftWhisper#21] opened 2023-08-10 05:12 UTC
<img width="1077" alt="Screenshot 2023-08-10 at 12 11 17 AM" src="https://github.com/exPHAT/SwiftWhisper/assets/9545735/2fb472d0-f145-4f65-a03d-7a617eabffcb">

How should I fix this problem to include the missing module whisper_cpp in the setup of the library for Swift because the other module is c++-based?  Thanks!

**Comment by exPHAT** [comment] 2023-08-10 11:09
This is usually caused by Xcode being weird. If you pulled from GitHub make sure to initialize submodules. Otherwise try clearing your derived data and build folder.

**Comment by shyamalschandra** [comment] 2023-08-10 12:51
Thank you!  I will check that out!

**Comment by exPHAT** [comment] 2023-08-12 20:04
Any luck?

**Comment by exPHAT** [comment] 2023-08-14 00:33
Closing for now. Let me know if this comes back up.

**Closed as not planned by exPHAT** 2023-08-14 00:33 UTC

**Comment by metinaltinbas** [comment] 2024-08-05 08:28
It still happens on extensions.
